name: Elixir CI/CD

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    # - name: Credo
    #   run: mix credo
    - name: Run Tests
      run: mix test
    - name: Build and publish docker image
      uses: whoan/docker-build-with-cache-action@v4
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: vorce/playlistlog
        image_tag: latest,${GITHUB_SHA}
        push_git_tag: true
        build_extra_args: "--build-arg=SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}"
