name: Elixir CI for PR

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.10.4-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Credo
      run: mix credo
    - name: Run Tests
      run: mix test